name: build-android 
on:
  push:
    branches:
      - main
      - add-ci
      - feature/add-android-ci

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global credential.helper store
      - run: | 
          cat <<EOF > $HOME/.git-credentials
          https://${{secrets.GITLAB_DEPLOY_TOKEN_USER}}:${{secrets.GITLAB_DEPLOY_TOKEN}}@gitlab.consolinno-it.de
          EOF
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - uses: timheuer/base64-to-file@v1
        id: write_keystore
        with:
          fileName: 'consolinno.keystore'
          encodedString: ${{ secrets.KEYSTORE }}
      - uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          target: 'android'
          modules: qtcharts
      #- uses: nttld/setup-ndk@v1
      #  with:
      #    ndk-version: r21e
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Install Android NDK
        run: sdkmanager  --install "ndk;21.4.7075529"
      - name: Set symlink to Android NDK
        run:  rm -rf /usr/local/lib/android/sdk/ndk-bundle; ln -f -s /usr/local/lib/android/sdk/ndk/21.4.7075529 /usr/local/lib/android/sdk/ndk-bundle
      #- uses: lhotari/action-upterm@v1
      #  env:
      #    KEYSTORE_PATH: ${{ steps.write_keystore.outputs.filePath }}
      #    SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      #    SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      #    SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: "Generating Snapshot version number"
        run: ./gen_snap_version.sh
      - run: ./build_android.sh
        env:
          KEYSTORE_PATH: ${{ steps.write_keystore.outputs.filePath }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Archive android apk and aab
        uses: actions/upload-artifact@v3
        with:
          name: Archive apk and aab
          path: |
            build/android/nymea-app/android-build/build/outputs/bundle/release/android-build-release.aab 
            build/android/nymea-app/android-build/build/outputs/apk/release/android-build-release-signed.apk
            build/android/nymea-app/android-build/build/outputs/apk/release/android-build-release-signed-apksigner.apk
