name: build-appimage 
on: 
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      whitelabel:
        description: 'Zu startende Elemente in der Matrix'
        required: true
        default: '["Consolinno-HEMS"]'
  #push:
  #  branches:
  #    - main
  #    - feature/appimage
  #    - experimental-build*
  #  tags:
  #    - 'v*'
jobs:
  build-appimage:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        WHITELABEL_TARGET: ${{ fromJSON(github.event.inputs.whitelabel) }}
    steps:
      - run: git config --global credential.helper store
      - run: | 
          cat <<EOF > $HOME/.git-credentials
          https://${{secrets.GITLAB_DEPLOY_TOKEN_USER}}:${{secrets.GITLAB_DEPLOY_TOKEN}}@gitlab.consolinno-it.de
          EOF
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          modules: 'qtcharts'
          target: 'desktop'
          extra: '--timeout 20'
      - run: |
          apt-get update && apt-get -y install fuse libfuse2
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod +x linuxdeployqt-*-x86_64.AppImage
#      - name: "Apply Consolinno patches"
#        run: ./apply_consolinno_patches.sh
      - name: "Generating Snapshot version number"
        run: ./gen_snap_version.sh
      - name: Install librsvg2-bin
        run: sudo apt install -y librsvg2-bin
      - name: Generating App Icons for ${{ matrix.WHITELABEL_TARGET }}
        env:
          WHITELABEL_TARGET: ${{ matrix.WHITELABEL_TARGET }}
        run: ./distribute_assets.sh
      - run: ./build_appimage.sh
        env:
          WHITELABEL_TARGET: ${{ matrix.WHITELABEL_TARGET }}
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3     
      #- uses: lhotari/action-upterm@v1
      - name: Archive AppImage for ${{ matrix.WHITELABEL_TARGET }}
        uses: actions/upload-artifact@v3
        with:
          name: Archive ${{ matrix.WHITELABEL_TARGET }} AppImage
          path: |
            build/appimage/*.AppImage
            build/appimage/firstRun.sh
          
  publish-appimage:
    name: Publish AppImage
    runs-on: ubuntu-latest
    needs: build-appimage
    if: github.ref_type == 'tag' #&& contains(github.ref_name, 'bla')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: Archive AppImage
      - name: Upload AppImage to release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ./*.AppImage
          tag: ${{ github.ref }}
          overwrite: true
