name: build-ios 
on:
  push:
    branches:
      - main
      - feature/add-ios-ci
      - feature/add-ios-publish      
      - feature/debug-ios-ci
      - feature/test-ios-ci

    tags:
      - 'v*'

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          
          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      - run: git config --global credential.helper store
      - run: | 
          cat <<EOF > $HOME/.git-credentials
          https://${{secrets.GITLAB_DEPLOY_TOKEN_USER}}:${{secrets.GITLAB_DEPLOY_TOKEN}}@gitlab.consolinno-it.de
          EOF
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          modules: 'qtcharts'
          host: 'mac'
          target: 'ios'
          arch: 'ios'
          extra: '--timeout 60'
      - name: "Upterm debug"
        if: contains(github.ref_name, 'debug<REMOVE-TO-ENABLE-AGAIN>') 
        uses: owenthereal/action-upterm@v1
        with:
          limit-access-to-actor: true
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
#      - name: "Apply Consolinno patches"
#        run: ./apply_consolinno_patches.sh
      - run: ./build_ios.sh
      #- uses: lhotari/action-upterm@v1
      - name: Archive .ipa
        uses: actions/upload-artifact@v3
        with:
          name: Archive .ipa
          path: build/ios/consolinno-hems.ipa 
          
  publish-ios:
    name: Publish iOS
    runs-on: macos-latest
    needs: build-ios
    if: github.ref_type == 'tag' #&& contains(github.ref_name, 'bla')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: Archive .ipa
      - name: Upload ipa package to release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ./*.ipa
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload .ipa to AppStore
        env:
          IOS_UPLOAD_USER: ${{ secrets.IOS_UPLOAD_USER }}
          IOS_UPLOAD_PASSWORD: ${{ secrets.IOS_UPLOAD_PASSWORD }}
        run: xcrun altool --type ios --upload-app --file consolinno-hems.ipa --username $IOS_UPLOAD_USER --password $IOS_UPLOAD_PASSWORD


