name: build-ios 
on:
  workflow_dispatch:
  push:
    #branches:
    #  - main
    #  - feature/add-ios-ci
    #  - feature/add-ios-publish      
    #  - debug-ios-ci
    #  - test-ios-ci
    #  - experimental-build-dynamic-whitelable

    tags:
      - 'v*'

jobs:
  build-ios:
    runs-on: macos-latest
    strategy:
      matrix:
        WHITELABEL_TARGET: ["Consolinno-HEMS", "Q.HOME-CONTROL", "Zewo-Dynamics"]
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}

          BUILD_CERTIFICATE_BASE64_QCELLS: ${{ secrets.BUILD_CERTIFICATE_BASE64_QCELLS }}
          P12_PASSWORD_QCELLS: ${{ secrets.P12_PASSWORD_QCELLS }}
          BUILD_PROVISION_PROFILE_BASE64_QCELLS: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64_QCELLS }}

          BUILD_CERTIFICATE_BASE64_ZEWOTHERM: ${{ secrets.BUILD_CERTIFICATE_BASE64_ZEWOTHERM }}
          P12_PASSWORD_ZEWOTHERM: ${{ secrets.P12_PASSWORD_ZEWOTHERM }}
          BUILD_PROVISION_PROFILE_BASE64_ZEWOTHERM: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64_ZEWOTHERM }}

          WHITELABEL_TARGET: ${{ matrix.WHITELABEL_TARGET }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          if [ "$WHITELABEL_TARGET" == "Q.HOME-CONTROL" ]; then
            BUILD_CERTIFICATE_BASE64_SELECTED=$BUILD_CERTIFICATE_BASE64_QCELLS
            P12_PASSWORD_SELECTED=$P12_PASSWORD_QCELLS
            BUILD_PROVISION_PROFILE_BASE64_SELECTED=$BUILD_PROVISION_PROFILE_BASE64_QCELLS

          elif [ "$WHITELABEL_TARGET" == "Zewo-Dynamics" ]; then
            BUILD_CERTIFICATE_BASE64_SELECTED=$BUILD_CERTIFICATE_BASE64_ZEWOTHERM
            P12_PASSWORD_SELECTED=$P12_PASSWORD_ZEWOTHERM
            BUILD_PROVISION_PROFILE_BASE64_SELECTED=$BUILD_PROVISION_PROFILE_BASE64_ZEWOTHERM

          else
            BUILD_CERTIFICATE_BASE64_SELECTED=$BUILD_CERTIFICATE_BASE64
            P12_PASSWORD_SELECTED=$P12_PASSWORD
            BUILD_PROVISION_PROFILE_BASE64_SELECTED=$BUILD_PROVISION_PROFILE_BASE64
          fi

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64_SELECTED" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64_SELECTED" | base64 --decode --output $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD_SELECTED" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          
          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      - run: git config --global credential.helper store
      - run: | 
          cat <<EOF > $HOME/.git-credentials
          https://${{secrets.GITLAB_DEPLOY_TOKEN_USER}}:${{secrets.GITLAB_DEPLOY_TOKEN}}@gitlab.consolinno-it.de
          EOF
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - name: "Upterm debug"
        if: contains(github.ref_name, 'debug-ios-ci') 
        uses: owenthereal/action-upterm@v1
        with:
          limit-access-to-actor: true
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}

          WHITELABEL_TARGET: ${{ matrix.WHITELABEL_TARGET }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
#      - name: "Apply Consolinno patches"
#        run: ./apply_consolinno_patches.sh
      - name: Install rsvg-convert
        run: |
          brew update
          brew install librsvg
      - name: Updating overlay.qrc for ${{ matrix.WHITELABEL_TARGET }}
        env:
          WHITELABEL_TARGET: ${{ matrix.WHITELABEL_TARGET }}
        run: ./scripts/update_overlay.sh
      - name: Generating App Icons for ${{ matrix.WHITELABEL_TARGET }}
        env:
          WHITELABEL_TARGET: ${{ matrix.WHITELABEL_TARGET }}
        run: ./distribute_assets.sh
      - run: ./build_ios.sh
        env:
          WHITELABEL_TARGET: ${{ matrix.WHITELABEL_TARGET }}
          PROVISIONING_PROFILE_ID_QCELLS: ${{ secrets.PROVISIONING_PROFILE_ID_QCELLS }}
          PROVISIONING_PROFILE_ID_ZEWOTHERM: ${{ secrets.PROVISIONING_PROFILE_ID_ZEWOTHERM }}
          PROVISIONING_PROFILE_ID_CONSOLINNO: ${{ secrets.PROVISIONING_PROFILE_ID_CONSOLINNO }}
      - name: Archive .ipa
        uses: actions/upload-artifact@v4
        with:
          name: Archive .ipa for ${{ matrix.WHITELABEL_TARGET }}
          path: |
            build/ios/*.ipa
            build/ios/Payload/*.app
          
  publish-ios:
    name: Publish iOS
    runs-on: macos-latest
    needs: build-ios
    if: github.ref_type == 'tag' #&& contains(github.ref_name, 'bla')
    strategy:
      matrix:
        WHITELABEL_TARGET: ["Consolinno-HEMS", "Q.HOME-CONTROL", "Zewo-Dynamics"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v4
        with:
          name: Archive .ipa for ${{ matrix.WHITELABEL_TARGET }}
      - name: Upload ipa package to release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ./*.ipa
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload .ipa to AppStore
        if: matrix.WHITELABEL_TARGET == 'Consolinno-HEMS'
        env:
          IOS_UPLOAD_USER: ${{ secrets.IOS_UPLOAD_USER }}
          IOS_UPLOAD_PASSWORD: ${{ secrets.IOS_UPLOAD_PASSWORD }}
        run: xcrun altool --type ios --upload-app --file consolinno-energy.ipa --username $IOS_UPLOAD_USER --password $IOS_UPLOAD_PASSWORD

