name: build-android 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    #  - experimental-build*
    tags:
      - 'v*'
jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #WHITELABEL_TARGET: ${{ fromJSON(github.event.inputs.whitelabel) }}
        WHITELABEL_TARGET: ["Consolinno-HEMS", "Q.HOME-CONTROL", "Zewo-Dynamics"]
    steps:
      - run: git config --global credential.helper store
      - run: | 
          cat <<EOF > $HOME/.git-credentials
          https://${{secrets.GITLAB_DEPLOY_TOKEN_USER}}:${{secrets.GITLAB_DEPLOY_TOKEN}}@gitlab.consolinno-it.de
          EOF
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - uses: timheuer/base64-to-file@v1
        id: write_keystore
        with:
          fileName: 'consolinno.keystore'
          encodedString: ${{ secrets.KEYSTORE }}
      #- uses: jurplel/install-qt-action@v3
        #with:
        #  version: '5.15.2'
        #  target: 'android'
        #  modules: qtcharts
        #  extra: '--timeout 20'
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17' 
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Install Android NDK
        run: sdkmanager --install "ndk;21.4.7075529" "platforms;android-34"
      - name: Set symlink to Android NDK
        run:  rm -rf /usr/local/lib/android/sdk/ndk-bundle; ln -f -s /usr/local/lib/android/sdk/ndk/21.4.7075529 /usr/local/lib/android/sdk/ndk-bundle
      - name: Patch build-tools 35.0 to support Gradle plugin 4.x  
        run: cp /usr/local/lib/android/sdk/build-tools/35.0.0/d8  /usr/local/lib/android/sdk/build-tools/35.0.0/dx &&  cp /usr/local/lib/android/sdk/build-tools/35.0.0/lib/d8.jar  /usr/local/lib/android/sdk/build-tools/35.0.0/lib/dx.jar
#      - uses: lhotari/action-upterm@v1
#        env:
#          KEYSTORE_PATH: ${{ steps.write_keystore.outputs.filePath }}
#          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
#          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
#          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
#          ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk-bundle
#      - name: "Apply Consolinno patches"
#        run: ./apply_consolinno_patches.sh
      - name: "Generating Snapshot version number"
        run: ./gen_snap_version.sh
      - name: Install librsvg2-bin
        run: sudo apt install -y librsvg2-bin
      - name: Generating App Icons for ${{ matrix.WHITELABEL_TARGET }}
        env:
          WHITELABEL_TARGET: ${{ matrix.WHITELABEL_TARGET }}
        run: ./distribute_assets.sh
      - run: ./build_android.sh
        env:
          KEYSTORE_PATH: ${{ steps.write_keystore.outputs.filePath }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk-bundle
          WHITELABEL_TARGET: ${{ matrix.WHITELABEL_TARGET }}
      - name: Cache apk in different dir
        run: |
          mkdir build/android/nymea-app/android-build/build/outputs/apk/signed
          cp build/android/nymea-app/android-build/build/outputs/apk/release/*-signed.apk build/android/nymea-app/android-build/build/outputs/apk/signed/
      #- run: ./build_android_testpatch.sh
      #  env:
      #    KEYSTORE_PATH: ${{ steps.write_keystore.outputs.filePath }}
      #    SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      #    SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      #    SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      #    ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk-bundle
      #    WHITELABEL_TARGET: ${{ matrix.WHITELABEL_TARGET }}
      - name: Move signed apk in combined dir
        run: cp build/android/nymea-app/android-build/build/outputs/apk/signed/*-signed.apk build/android/nymea-app/android-build/build/outputs/apk/release/
      - name: Archive android apk and aab
        uses: actions/upload-artifact@v4
        with:
          name: Archive apk and aab for ${{ matrix.WHITELABEL_TARGET }}
          path: |
            build/android/nymea-app/android-build/build/outputs/bundle/release/*.aab
            build/android/nymea-app/android-build/build/outputs/apk/release/*.apk
            build/android/nymea-app/android-build/build/outputs/apk/release/${{ matrix.WHITELABEL_TARGET }}-*-testing.apk

  publish-android:
    name: Publish android packages
    runs-on: ubuntu-latest
    needs: build-android
    if: github.ref_type == 'tag' #&& contains(github.ref_name, 'bla')
    strategy:
      matrix:
        WHITELABEL_TARGET: ["Consolinno-HEMS", "Q.HOME-CONTROL", "Zewo-Dynamics"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v4
        with:
          name: Archive apk and aab for ${{ matrix.WHITELABEL_TARGET }}
      - name: Upload .apk to release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: apk/release/*.apk
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload .aab to release for ${{ matrix.WHITELABEL_TARGET }}
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: bundle/release/*.aab
          tag: ${{ github.ref }}
          overwrite: true

