name: build-appimage 
on:
  push:
    branches:
      - main
      - feature/appimage
      - experimental-build*
    tags:
      - 'v*'
jobs:
  build-appimage:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        WHITELABEL_TARGET: ["Consolinno-HEMS"]
    steps:
      - run: git config --global credential.helper store
      - run: | 
          cat <<EOF > $HOME/.git-credentials
          https://${{secrets.GITLAB_DEPLOY_TOKEN_USER}}:${{secrets.GITLAB_DEPLOY_TOKEN}}@gitlab.consolinno-it.de
          EOF
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          modules: 'qtcharts'
          target: 'desktop'
          extra: '--timeout 20'
      - run: |
          apt-get update && apt-get -y install fuse libfuse2
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod +x linuxdeployqt-*-x86_64.AppImage
#      - name: "Apply Consolinno patches"
#        run: ./apply_consolinno_patches.sh
      - run: ./build_appimage.sh
        env:
          WHITELABEL_TARGET: ${{ matrix.WHITELABEL_TARGET }}
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3     
      #  run: ./gen_snap_version.sh
      #- uses: lhotari/action-upterm@v1
      - name: Archive AppImage for ${{ matrix.WHITELABEL_TARGET }}
        uses: actions/upload-artifact@v3
        with:
          name: Archive AppImage
          path: build/appimage/*.AppImage
          
  publish-appimage:
    name: Publish AppImage
    runs-on: ubuntu-latest
    needs: build-appimage
    if: github.ref_type == 'tag' #&& contains(github.ref_name, 'bla')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: Archive AppImage
      - name: Upload AppImage to release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ./*.AppImage
          tag: ${{ github.ref }}
          overwrite: true
