name: build-android 
on: [push]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global credential.helper store
      - run: | 
          cat <<EOF > $HOME/.git-credentials
          https://${GITLAB_DEPLOY_TOKEN_USER}:${GITLAB_DEPLOY_TOKEN}@gitlab.consolinno-it.de
          EOF
      - uses: lhotari/action-upterm@v1
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          target: 'android'
          modules: qtcharts
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: android-actions/setup-android@v2
      - run: ls
