name: Publish
on:
  push:
    tags:
      - 'v*'
      - 'test-publish-v*'

      
jobs:
  publish:
    name: Publish the package
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build and private release
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'Publish the package'
          repo-token: ${{ secrets.GH_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success,skipped,cancelled,failure
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GH_TOKEN}}
          workflow: build_windows.yml  
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GH_TOKEN}}
          workflow: build_appimage.yml
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GH_TOKEN}}
          workflow: build_android.yml 
#      - uses: dawidd6/action-download-artifact@v2
#        with:
#          github_token: ${{secrets.GH_TOKEN}}
#          workflow: build_snap.yml    
      - name: Create release in public repo
        uses: ncipollo/release-action@v1
        with:
          repo: consolinno-hems-app
          owner: ConsolinnoEnergy
          omitBody: true
          removeArtifacts: true
          token: ${{ secrets.REPO_GITLAB_TOKEN }}
          #artifacts: "Archive snap package/*.snap,Consolinno HEMS windows installer/*.exe"
          artifacts: "Archive AppImage/*.AppImage, Consolinno HEMS windows installer/*.exe, Archive apk and aab/apk/release/consolinno-hems-*.apk"
